replicas: 3
port: 27017

replicaSetName: rs0

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

persistentVolume:
  # storageClass: pd-ssd
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
