---
# Modified from https://github.com/microservices-demo/microservices-demo
# Please see this repository for the original

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: sock-shop
spec:
  replicas: 6
  selector:
    matchLabels:
      name: front-end
      version: 0.2.0
  template:
    metadata:
      labels:
        name: front-end
        version: 0.2.0
        affinity-version: "3"
    spec:
      containers:
      - name: front-end
        image: weaveworksdemos/front-end:0.3.12
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
        env:
        - name: SESSION_REDIS
          value: "true"
        ports:
        - containerPort: 8079
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - { key: name, operator: In, values: [ front-end ] }
                - { key: affinity-version, operator: In, values: [ "3" ] }
              topologyKey: kubernetes.io/hostname
